### ISSUE TITLE
如何得到 test_pile_loss_1m.csv？

### ISSUE THREAD

**Issue by YWMditto** [sail-sg/regmix#1]
非常棒的工作！
请问如何得到 test_mixture_1m.csv 和 test_pile_loss_1m.csv，再训练256个比例得到吗？（相比于用于拟合的已有的512个训练比例和loss）

**Comment by SivilTaram** [comment]
@YWMditto 感谢你的关注，是的，这256个比例不能在train里出现过（否则就不是test了），可以用我们code里的`sort_and_deduplciate`函数去一下重复～（https://github.com/sail-sg/regmix/blob/124b971f9b9d626ff08d562b20c211c903ce534b/mixture_config/synthesize_mixture.py#L253）。

**Comment by YWMditto** [comment]
了解，十分感谢！
