### ISSUE TITLE
step1-mixture, 由于占比过小，类别在随机后变成了0

### ISSUE THREAD

**Issue by feifei2023** [sail-sg/regmix#10]
某类在占比中不到0.1%，所以建立512个随机weight时，大部分weight中该类别都变成了0，请问这个怎么处理？

**Comment by xszheng2020** [comment]
Hi, @feifei2023 , thanks for your interest in our work.

First, you can adjust the lower bound of [number_bound](https://github.com/sail-sg/regmix/blob/main/mixture_config/synthesize_mixture.py#L130) to a value larger than 0.0 to reject such weights.

Second, you can tune the Temperature for the prior distribution and Strength for the dirichlet distribution to generate more dynamic weights.

**Comment by feifei2023** [comment]
> Hi, @feifei2023 , thanks for your interest in our work.
> 
> First, you can adjust the lower bound of [number_bound](https://github.com/sail-sg/regmix/blob/main/mixture_config/synthesize_mixture.py#L130) to a value larger than 0.0 to reject such weights.
> 
> Second, you can tune the Temperature for the prior distribution and Strength for the dirichlet distribution to generate more dynamic weights.

after adjusting the lower bound to min of prior_dist, there will be easy to get [final_samples=0](https://github.com/sail-sg/regmix/blob/20ae8dbd2b58a6f5130a9e61e56ed6e17e4c6476/mixture_config/synthesize_mixture.py#L178)

**Comment by xszheng2020** [comment]
> > Hi, @feifei2023 , thanks for your interest in our work.
> > First, you can adjust the lower bound of [number_bound](https://github.com/sail-sg/regmix/blob/main/mixture_config/synthesize_mixture.py#L130) to a value larger than 0.0 to reject such weights.
> > Second, you can tune the Temperature for the prior distribution and Strength for the dirichlet distribution to generate more dynamic weights.
> 
> after adjusting the lower bound to minimum of prior_dist, there will be easy to get [final_samples=0](https://github.com/sail-sg/regmix/blob/20ae8dbd2b58a6f5130a9e61e56ed6e17e4c6476/mixture_config/synthesize_mixture.py#L178)

This could be expected. 
You may tune the Temperature for the prior distribution and Strength for the dirichlet distribution in synthesize_mixture.py to generate more dynamic weights to avoid rejection.
