### ISSUE TITLE
Could you please upload the requirements.txt?

### ISSUE THREAD

**Issue by shuxiaobo** [sail-sg/regmix#2]
Could you please upload the requirements.txt?

**Comment by SivilTaram** [comment]
@shuxiaobo Hello! Which folder do you refer to? I'm pleased to provide the requirements.txt file.

**Comment by shuxiaobo** [comment]
@SivilTaram Hi~ thanks for your reply. I see the requirements.txt in model_training, but `ModuleNotFoundError: No module named 'xentropy_cuda_lib'` here is a module is missing

**Comment by SivilTaram** [comment]
@shuxiaobo Hello! Do you follow the instructions to install xformers first?

**Comment by shuxiaobo** [comment]
I've solve the problem, thanks a lot
