### ISSUE TITLE
So many data files after tokenizing

### ISSUE THREAD

**Issue by shuxiaobo** [sail-sg/regmix#3]
Here is so many many many files in the processed dir when I run the `run_preprocess.sh`, the chunk size is `2049 *256` cause the problem, it will make the dir unable to `ls` and `read` even `rm`, is there any solution for this?

**Comment by SivilTaram** [comment]
You can use python to get what you want:

```python
def get_prefix(folder_path):
    # read all files in the folder
    all_files = os.listdir(folder_path)
    # shuffle
    random.shuffle(all_files)
    all_files = [file_path for file_path in all_files if "train" in file_path]
    print(all_files[:10])
```

**Comment by SivilTaram** [comment]
@shuxiaobo Hi, does this solve your problem?

**Comment by shuxiaobo** [comment]
@SivilTaram Thanks for your reply. I've down sample the data to 10B token, which result in 83668 files, this scale make the load success

**Comment by SivilTaram** [comment]
@shuxiaobo Glad to hear that!
