### ISSUE TITLE
Loss计算咨询

### ISSUE THREAD

**Issue by zhaochs1995** [sail-sg/regmix#4]
1. 请问train_pile_loss，是否为每种mixture比例情况下，代理模型各在valid数据集上的loss损失？为什么**config/n**x.yaml中valid数据集有17种，train_pile_loss中验证集只有13个呢？
2. 请问test_pile_loss是如何生成的呢？
3. regression.ipynb中，target来源为pd.read_csv("data/train_pile_loss_1m.csv")，包含了the_pile_pile_cc_val_loss在内的13种数据。为什么repo说"By default we use the Pile-CC validation loss as the target"，只用了pile_cc？

**Comment by SivilTaram** [comment]
@zhaochs1995 
Hello, 谢谢你对我们工作的关注，我依次回答一下问题：
1. 是的，没错。只有13个log的原因是早期的时候我们的codebase follow TinyLlama会一次试图读入8个文件，如果遇到数据量极少的domain 就会因为读不够8个文件导致training中断。后来我们给代码加了一个自动跳过数据量极少domain的逻辑，因此有些domain在wandb上不会有log。
2. test_pile_loss和train 的生成方法一样，你可以先生成比如700个，确保data mixture都不一样，然后把train放500个，test放200个。这700个都要实际跑实验拿到validation loss。
3. Pile-CC 是最diverse且最有代表性的domain。优化Pile-CC loss可以最快优化general 下游任务的性能。

**Comment by zhaochs1995** [comment]
非常棒的工作，多谢解答
