### ISSUE TITLE
A question regarding data preprocessing.

### ISSUE THREAD

**Issue by Zhang-Mozhi** [sail-sg/regmix#5]
I am particularly intrigued by the methodology used in your paper. However, I want to inquire whether you have performed deduplication on the Pile dataset, as it seems not be explicitly mentioned in your paper. Best Regards.

**Comment by SivilTaram** [comment]
@Zhang-Mozhi Hello! Thanks for your question! We do not do deduplication on the Pile dataset since the deduplicated version cannot be splitted into different domains (metadata removed). The full dataset used in our experiment can be found at https://huggingface.co/datasets/sail/regmix-data

**Comment by Zhang-Mozhi** [comment]
@SivilTaram Thanks for the reply!
